// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH_XXYwgjJNNyM91ES8GnEzpJrZcAHVGQ',
    appId: '1:358712127461:web:a134e8fc2317832ab8490c',
    messagingSenderId: '358712127461',
    projectId: 'testlogin-2c190',
    authDomain: 'testlogin-2c190.firebaseapp.com',
    storageBucket: 'testlogin-2c190.appspot.com',
    measurementId: 'G-ZWCW5P2B6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhAlaDVUCoZvNWBShKZmmg3I_MvZnEeo',
    appId: '1:358712127461:android:649888c9bb5488b9b8490c',
    messagingSenderId: '358712127461',
    projectId: 'testlogin-2c190',
    storageBucket: 'testlogin-2c190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHKCW6SRdi7hGWbx3zm25U1i565yPKVk',
    appId: '1:358712127461:ios:1a190f3a187169bab8490c',
    messagingSenderId: '358712127461',
    projectId: 'testlogin-2c190',
    storageBucket: 'testlogin-2c190.appspot.com',
    iosBundleId: 'com.example.testlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHKCW6SRdi7hGWbx3zm25U1i565yPKVk',
    appId: '1:358712127461:ios:2771938361e38188b8490c',
    messagingSenderId: '358712127461',
    projectId: 'testlogin-2c190',
    storageBucket: 'testlogin-2c190.appspot.com',
    iosBundleId: 'com.example.testlogin.RunnerTests',
  );
}
